export const styles = {
  appContainer: { minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", backgroundColor: "#2d3748", fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif' },
  mobileFrame: { width: "375px", height: "800px", backgroundColor: "#ffffff", borderRadius: "40px", border: "12px solid #1a202c", overflow: "hidden", position: "relative", display: "flex", flexDirection: "column", boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.5)" },
  statusBar: { height: "40px", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0 20px", fontSize: "12px", fontWeight: "bold", userSelect: "none", zIndex: 50 },
  contentContainer: { flex: 1, overflowY: "auto", position: "relative", display: "flex", flexDirection: "column" },
  header: { padding: "16px", backgroundColor: "white", position: "sticky", top: 0, zIndex: 10, borderBottom: "1px solid #f0f0f0", display: "flex", justifyContent: "space-between", alignItems: "center" },
  bottomNav: { height: "80px", borderTop: "1px solid #e2e8f0", display: "flex", justifyContent: "space-around", alignItems: "flex-start", paddingTop: "12px", backgroundColor: "white", position: "sticky", bottom: 0, zIndex: 20 },
  navItem: { display: "flex", flexDirection: "column", alignItems: "center", background: "none", border: "none", cursor: "pointer", color: "#94a3b8", fontSize: "10px", fontWeight: 600 },
  card: { backgroundColor: "white", borderRadius: "16px", padding: "16px", marginBottom: "12px", boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1)", border: "1px solid #f1f5f9", display: "flex", alignItems: "center", cursor: "pointer", width: "100%", textAlign: "left" },
  scheduleCard: { backgroundColor: "white", borderRadius: "16px", padding: "16px", marginBottom: "12px", boxShadow: "0 2px 5px rgba(0,0,0,0.05)", border: "1px solid #f1f5f9", borderLeft: "5px solid #0ea5e9", display: "flex", justifyContent: "space-between", alignItems: "center" },
  statusCard: { borderRadius: "16px", padding: "16px", marginBottom: "20px", display: "flex", justifyContent: "space-between", alignItems: "center", transition: "all 0.3s ease", cursor: "pointer", border: "1px solid transparent" },
  floorTabContainer: { display: "flex", justifyContent: "space-around", backgroundColor: "#f1f5f9", padding: "4px", borderRadius: "12px", margin: "0 24px 16px 24px" },
  floorTab: { flex: 1, padding: "8px", textAlign: "center", borderRadius: "10px", fontSize: "13px", fontWeight: "bold", cursor: "pointer", transition: "all 0.2s" },
  addButton: { width: "100%", padding: "14px", backgroundColor: "white", color: "#0ea5e9", border: "2px dashed #bae6fd", borderRadius: "16px", fontWeight: "bold", fontSize: "14px", cursor: "pointer", marginTop: "10px", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px" },
  buttonPrimary: { width: "100%", padding: "16px", backgroundColor: "#10b981", color: "white", border: "none", borderRadius: "16px", fontWeight: "bold", fontSize: "16px", cursor: "pointer", marginTop: "10px", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px" },
  buttonSecondary: { width: "100%", padding: "16px", backgroundColor: "white", color: "#334155", border: "2px solid #e2e8f0", borderRadius: "16px", fontWeight: "bold", fontSize: "16px", cursor: "pointer", marginTop: "10px", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px" },
  buttonYellow: { width: "100%", padding: "16px", backgroundColor: "#facc15", color: "#1e293b", border: "none", borderRadius: "16px", fontWeight: "bold", fontSize: "16px", cursor: "pointer", marginTop: "10px", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px" },
  input: { width: "100%", padding: "14px", borderRadius: "12px", border: "1px solid #cbd5e1", fontSize: "16px", marginTop: "8px", marginBottom: "8px", boxSizing: "border-box" },
  mapGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px", padding: "24px" },
  roomBtn: { padding: "10px", borderRadius: "12px", border: "2px solid #e2e8f0", backgroundColor: "white", height: "160px", display: "flex", flexDirection: "column", justifyContent: "space-between", cursor: "pointer", overflow: "hidden" },
  roomBtnActive: { borderColor: "#10b981", backgroundColor: "#ecfdf5" },
  chatBubble: { padding: "12px 16px", borderRadius: "16px", maxWidth: "80%", marginBottom: "12px", fontSize: "14px", lineHeight: "1.4" },
  chatUser: { backgroundColor: "#10b981", color: "white", alignSelf: "flex-end", borderBottomRightRadius: "0" },
  chatBot: { backgroundColor: "white", color: "#334155", alignSelf: "flex-start", borderBottomLeftRadius: "0", border: "1px solid #e2e8f0" },
  modalOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100, padding: '24px' },
  modalCard: { backgroundColor: 'white', borderRadius: '24px', padding: '32px 24px 16px 24px', width: '100%', textAlign: 'center', boxShadow: '0 10px 25px rgba(0,0,0,0.2)' },
  modalIcon: { display: 'flex', justifyContent: 'center', marginBottom: '16px' },
  modalTitle: { fontSize: '18px', fontWeight: '800', color: '#1e293b', marginBottom: '16px', textTransform: 'uppercase' },
  modalText: { fontSize: '15px', color: '#475569', marginBottom: '12px', lineHeight: '1.5' },
  modalSubText: { fontSize: '13px', color: '#94a3b8', marginBottom: '24px', lineHeight: '1.4' },
  modalDivider: { height: '1px', backgroundColor: '#e2e8f0', marginBottom: '8px' },
  modalButton: { width: '100%', padding: '16px', background: 'none', border: 'none', color: '#0ea5e9', fontWeight: 'bold', fontSize: '15px', cursor: 'pointer', borderBottom: '1px solid #f1f5f9' },
  modalButtonLast: { borderBottom: 'none' },
  logEntry: { backgroundColor: 'white', padding: '12px', borderRadius: '12px', marginBottom: '8px', border: '1px solid #e2e8f0', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  facultyRow: { backgroundColor: 'white', padding: '16px', borderRadius: '12px', marginBottom: '8px', border: '1px solid #f1f5f9', display: 'flex', justifyContent: 'space-between', alignItems: 'center', boxShadow: '0 1px 2px rgba(0,0,0,0.05)' },
  roomListCard: { backgroundColor: 'white', padding: '16px', borderRadius: '12px', marginBottom: '8px', border: '1px solid #f1f5f9', boxShadow: '0 1px 2px rgba(0,0,0,0.05)' },
  instructionStep: { display: 'flex', gap: '16px', marginBottom: '20px', alignItems: 'flex-start' },
  instructionNum: { width: '24px', height: '24px', borderRadius: '50%', backgroundColor: '#e0f2fe', color: '#0284c7', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '12px', fontWeight: 'bold', flexShrink: 0 },
  buttonAdmin: { width: "100%", padding: "16px", backgroundColor: "#334155", color: "white", border: "none", borderRadius: "16px", fontWeight: "bold", fontSize: "16px", cursor: "pointer", marginTop: "10px", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px" },
};